name = "WaveMC"
uuid = "f85d90cf-446f-419e-8ce8-0b41d8173ef7"
version = "0.1.0"
authors = ["Andreas Feuerpfeil <development@manybodylab.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Carlo = "780c37f4-4e5a-43de-9e79-65c261e525a4"
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
CairoMakie = "0.15.8"
Carlo = "0.3.1"
ChunkSplitters = "3.1.2"
DataFrames = "1.8.1"
Distributions = "0.25.123"
HDF5 = "0.17.2"
Printf = "1.11.0"
Random = "1.11.0"
ThreadsX = "0.1.12"
julia = "1.10"
