[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
WaveMC = "f85d90cf-446f-419e-8ce8-0b41d8173ef7"

[compat]
Documenter = "1"
Literate = "2"
WaveMC = "0.1"