name: 'Format'

on:
  pull_request_target:
    paths: ['**/*.jl']
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  actions: write
  pull-requests: write

jobs:
  formatcheck:
    uses: "ManyBodyLab/ManyBodyLabActions/.github/workflows/FormatCheck.yml@main"